apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: mycontainer
      image: redis
      env:
        - name: ENCODED_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: username
        - name: ENCODED_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: password
  # Add other specifications like volumes, restartPolicy, etc. if needed
