apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
spec:
  ports:
  - port: 80
    nodePort: 30001
    targetPort:  vproapp-port
    protocol: TCP
  selector:
    app: vproappippa
  type: NodePort
